#!/bin/sh
#
# /etc/init.d/svnsf2github
# Subsystem file for "svnsf2github.sh" server
#
# chkconfig: 2345 95 05
# description: svnsf2github server daemon to push a SVN SourceForge repository modifications to a Github mirror
#
# processname: svnsf2github.sh
# pidfile: /var/run/svnsf2github.pid

RETVAL=0
prog="svnsf2github"

start() {
	echo -n $"Starting $prog:"
	/home/rbouqueau/Works/gpac/svnsf2github.sh &
	RETVAL=$?
	[ "$RETVAL" = 0 ] && touch /var/lock/subsys/$prog
	echo
}

stop() {
	echo -n $"Stopping $prog:"
	killproc $prog -TERM
	RETVAL=$?
	[ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
	echo
}

reload() {
	echo -n $"Reloading $prog:"
	killproc $prog -HUP
	RETVAL=$?
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	reload)
		reload
		;;
	status)
		status $prog
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}"
		RETVAL=1
esac
exit $RETVAL
